# Generated by Django 4.1.4 on 2023-01-26 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='doe',
            field=models.DateField(default=datetime.datetime(2023, 1, 26, 16, 7, 47, 235110)),
            preserve_default=False,
        ),
    ]
